# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d675818f90f75c707cefd73a15e0c09a13f56b80797e1c2382e7002629517cd43b3fbfd07dc34ea08997610baa30091def78e656b9e9a35e239b2b53679e644c

test:
  secret_key_base: 1905dcc58c232eaf8e73670538c83d36038517caf81b64abc6c9c9acc40fd6892568518795e95d960ec223ab5eab9fd918b87cb8e3b4367492151274fe176e1f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
